env:
  es2020: true
  node: true
extends:
  - airbnb-typescript/base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 11
  sourceType: module
  project: './tsconfig.json'
plugins:
  - '@typescript-eslint'
rules:
#  indent: "off"
  "@typescript-eslint/indent":
    - error
    - 4
  class-methods-use-this: off
  no-plusplus: off
